name: Dev Mobile Pipeline

on:
  push:
    branches: ["dev"]
  workflow_dispatch: {}

concurrency:
  cancel_in_progress: true
  group: ${{ workflow.filename }}-${{ github.ref }}

jobs:
  quality_dev:
    name: Dev Quality Gates
    environment: development
    steps:
      - uses: eas/checkout
      - uses: eas/install_node_modules
      - name: Validate EAS workflows
        run: |
          npx eas workflow:validate .eas/workflows/dev.yml --non-interactive
          npx eas workflow:validate .eas/workflows/main.yml --non-interactive
          npx eas workflow:validate .eas/workflows/update-pr.yml --non-interactive
      - name: Lint
        run: npm run lint
      - name: Type check
        run: npm run check:types
      - name: Unit tests
        run: npm test
      - name: Server tests
        run: npm run test:server
      - name: Backend build validation
        run: npm run server:nest:build

  update_dev:
    name: Publish Dev OTA (Expo Go)
    needs: [quality_dev]
    if: ${{ github.event_name == 'push' }}
    type: update
    environment: development
    params:
      branch: dev
      platform: all
      message: ${{ github.commit_message || github.sha }}

  build_dev_android:
    name: Build Dev Android (internal APK)
    needs: [quality_dev]
    if: ${{ github.event_name == 'push' }}
    type: build
    environment: development
    env:
      EAS_USE_CACHE: "1"
    params:
      platform: android
      profile: development
      message: ${{ github.commit_message || github.sha }}
